spring:
  application:
    name: wb-singed-url

security:
  oauth2:
    resource:
      user-info-uri: https://dev-182628.oktapreview.com/oauth2/aus9jwgocbajDoyVq0h7/v1/userinfo

s3:
  bucket:
    name: wb-poc-trans-input
